import { CompaniesThreadProps } from "../../components/CompaniesThread";
import a167 from "../../../public/assets/images/companies/a16z.svg";
import si from "../../../public/assets/images/companies/si.svg";
import generate from "../../../public/assets/images/companies/generate.svg";
import accel from "../../../public/assets/images/companies/accel.svg";
import index from "../../../public/assets/images/companies/index.svg";
import qed from "../../../public/assets/images/companies/qed.svg";
import gradient from "../../../public/assets/images/companies/gradient.svg";
import sequoia from "../../../public/assets/images/companies/sequoia.svg";
import alumni from "../../../public/assets/images/companies/alumni.svg";

export const companiesThreadData: CompaniesThreadProps = {
  companies: [
    // thread 1==========================================================================
    {
      comp1: {
        img: a167,
        name: "A16z",
        deals: 6,
        value: "$1253.1m",
        leadDays: 247.8,
        details1: {
          subTitle: "Kobold Metals",
          stage: "Series B",
          raised: "407.5m",
          co_investors: [
            "T. Rowe Price",
            "Standard Investments",
            "Mitsubishi Corporation",
            "July Fund",
            " Equinor Ventures",
            " Earthshot Ventures",
            " Breakthrough Energy Ventures",
            "Bond",
            " Mary Meeker",
            "BHP Ventures",
            " Keenan Jennings",
            "Andreessen Horowitz (Connie Chan)",
          ],
        },
        details2: {
          subTitle: "Payrails",
          stage: "Seed",
          raised: "20.8m",
          co_investors: [
            "HV Capital (Barbod Namini)",
            "General Catalyst (Zeynep Yavuz)",
            "EQT Ventures (Kaushik Subramanian)",
            "Andreessen Horowitz (David Haber)",
          ],
        },
        details3: {
          subTitle: "finres [25073]",
          stage: "Seed",

          co_investors: [
            "Tiny VC",
            "Kima Ventures",
            "Raise Sherpas",
            "Plug and Play Ventures",
            "Illuminate Financial",
            "Better Angle",
            " AFI Ventures",
          ],
        },
        details4: {
          subTitle: "Radiant",
          stage: " Series B",
          raised: "4.5m",
          co_investors: [
            "McKinley Capital Management",
            " Founders Fund (Scott Nolan)",
            "Draper Associates",
            "Decisive Point",
            "Cantos",
            "Boost VC",
            "Andreessen Horowitz (David Ulevitch)",
          ],
        },
        details5: {
          subTitle: "Skydio",
          stage: " Series E",
          raised: "570m",
          co_investors: [
            "UP Partners",
            "NVIDIA",
            " Linse Capital (Bastiaan Janmaat)",
            " IVP (Todd Chaffee)",
            " Hercules Capital",
            " DoCoMo Capital",
            "Axon (Henrik Kühl)",
            "Andreessen Horowitz (David Ulevitch)",
          ],
        },
        details6: {
          subTitle: "Stoïk",
          stage: "Series A",
          raised: " 24.8m",
          co_investors: [
            "Opera Tech Ventures (Thibaut Schlaeppi)",
            "Munich Re Ventures (Ben Bergsma)",
            "Andreessen Horowitz (Seema Amble)",
            "Alven (Thomas Cuvelier)",
          ],
        },
        details7: {
          subTitle: "Headway",
          stage: " Series C",
          raised: "225.5m",
          co_investors: [
            "Thrive Capital",
            "Spark Capital (Will Reed)",
            "Health Care Service Corporation",
            "Andreessen Horowitz (Scott Kupor)",
            " Accel",
          ],
        },
      },
      comp3: {
        img: "",
        name: "",
        deals: 0,
        value: "",
        leadDays: 0,
      },
      comp5: {
        img: "",
        name: "",
        deals: 0,
        value: "",
        leadDays: 0,
      },
      comp6: {
        img: "",
        name: "",
        deals: 0,
        value: "",
        leadDays: 0,
      },
    },
    // second thread ----------------------------------------------------------------------------------
    {
      comp3: {
        img: si,
        name: "SpeedInvest",
        deals: 5,
        value: "$73.8m",
        leadDays: 99.8,
        details1: {
          subTitle: "FERNRIDE [20511]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Fly Ventures",
            "Schenker Ventures",
            "PUSH Ventures",
            " Promus Ventures",
            "KRONE",
            "HHLA Next",
            "10x Founders",
          ],
        },
        details2: {
          subTitle: "Riverse [21917]",
          stage: "Seed",
          raised: "",
          co_investors: ["Techstars", "Evolem Start"],
        },
        details3: {
          subTitle: "finres [25073]",
          stage: "Seed",

          co_investors: [
            "Tiny VC",
            "Kima Ventures",
            "Raise Sherpas",
            "Plug and Play Ventures",
            "Illuminate Financial",
            "Better Angle",
            " AFI Ventures",
          ],
        },
        details4: {
          subTitle: "Fairlyne [28585]",
          stage: " Seed",
          raised: "",
          co_investors: ["Kima Ventures", "FJ Labs "],
        },
        details5: {
          subTitle: "blocktorch [145]",
          stage: " Seed",
          raised: "",
          co_investors: [
            "Rockaway Blockchain Fund",
            "Remote First Capital",
            "IDEO CoLab",
            "Entrepreneur First",
            "Alchemy Ventures",
          ],
        },
      },

      comp4: {
        img: "",
        name: "",
        deals: 0,
        value: "",
        leadDays: 0,
      },
      comp5: {
        img: generate,
        name: "General Catalyst",
        deals: 9,
        value: "$878.4",
        leadDays: 136.7,
        details1: {
          subTitle: "Disclo",
          stage: " Seed",
          raised: "6.6m",
          co_investors: [
            "Y Combinator",
            "Lerer Hippeau (Andrea Hippeau)",
            " General Catalyst",
            "Gaingels",
            "Bain Capital Ventures (Sarah Hinkfuss)",
          ],
        },
        details2: {
          subTitle: "Lemonade",
          stage: " Post-IPO Equity",
          raised: "631.5m",
          co_investors: ["General Catalyst (Joel Cutler)"],
        },
        details3: {
          subTitle: "Payrailsz",
          stage: "Seed",
          raised: "20.8m",
          co_investors: [
            "HV Capital (Barbod Namini)",
            " General Catalyst (Zeynep Yavuz)",
            "EQT Ventures (Kaushik Subramanian)",
            "Andreessen Horowitz (David Haber)",
          ],
        },
        details4: {
          subTitle: "Luma AI",
          stage: " Series A",
          raised: "25.5m",
          co_investors: [
            "South Park Commons (Bala Chandrasekaran)",
            " NVIDIA (Mohamed Siddeek)",
            " Matrix Partners (Antonio Rodriguez)",
            "General Catalyst",
            " Andreas Klinger",
            "Amplify Partners (David Beyer, Mike Dauber)",
          ],
        },
        details5: {
          subTitle: "Finch",
          stage: " Series B",
          raised: " 62.1m",
          co_investors: [
            "QED Investors",
            "PruVen Capital",
            "Menlo Ventures (Croom Beatty)",
            "General Catalyst (Alex Tran)",
            "Altman Capital",
          ],
        },
        details6: {
          subTitle: "Mosaic.tech",
          stage: " Series C",
          raised: "71.9m",
          co_investors: [
            "XYZ Venture Capital",
            "OMERS Ventures (Eugene Lee)",
            "General Catalyst",
            "Friends & Family Capital (Colin Anderson)",
          ],
        },
        details7: {
          subTitle: "Neko Health",
          stage: " Series A",
          raised: "60m",
          co_investors: [
            "Lakestar (Klaus Hommels)",
            "General Catalyst",
            "Atomico (Niklas Zennström)",
          ],
        },
      },
      comp6: {
        img: "",
        name: "",
        deals: 0,
        value: "",
        leadDays: 0,
      },
    },
    // third thread ---------------------------------------------------------------------------------
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp4: {
        img: accel,
        name: "Accel",
        deals: 9,
        value: "$809.8m",
        leadDays: 140.3,

        details1: {
          subTitle: "cyera [378]",
          stage: "Series B",
          raised: "",
          co_investors: ["Redpoint", "Cyberstarts", "Sequoia Capital"],
        },
        details2: {
          subTitle: "insify [379]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Visionaries Club",
            "Opera Tech Ventures",
            "Munich Re Ventures",
            "Frontline Ventures",
            "BNP Paribas",
          ],
        },

        details3: {
          subTitle: "wallapop [7460]",
          stage: "Series G",
          raised: "",
          co_investors: ["Naver", "Insight Partners", "14W"],
        },
        details4: {
          subTitle: "rex app [912]",
          stage: "Seed",
          raised: "",
          co_investors: ["Khosla Ventures", "Future Positive"],
        },
        details5: {
          subTitle: "Fortify [21372]",
          stage: "Venture Round",
          raised: "",
          co_investors: [
            "RTX Ventures",
            "Prelude Ventures",
            "Ocean Azul Partners",
            "Neotribe Ventures",
            "Mainspring Capital",
            "Lockheed Martin",
            "Cota Capital",
          ],
        },
        details6: {
          subTitle: "linear [4662]",
          stage: "Series B",
          raised: "",
          co_investors: ["Sequoia Capital", "01 Advisors"],
        },
        details7: {
          subTitle: "Agave API [17921]",
          stage: "Seed",
          raised: "",
          co_investors: ["Mischief Discovery"],
        },
        details8: {
          subTitle: "catch+release [7564]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Stagwell",
            "HarbourVest Partners",
            "Cervin Ventures",
            "Astia",
            "35V",
          ],
        },
        details9: {
          subTitle: "headway [7542]",
          stage: "Series C",
          raised: "",
          co_investors: [
            "Thrive Capital",
            "Spark Capital",
            "Health Care Service Corporation",
            "Andreessen Horowitz",
          ],
        },
      },
    },
    // fourth thread ----------------------------------------------------------------------------------
    {
      comp1: {
        img: gradient,
        name: "Gradient Ventures",
        deals: 3,
        value: "$809.8m",
        leadDays: 186,

        details1: {
          subTitle: "spline [4687]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Y Combinator",
            "NXTP Ventures",
            "First Round Capital",
            "Chapter One Ventures",
            "Backend Capita",
          ],
        },
        details2: {
          subTitle: "lambda [10469]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Mercato Partners",
            "Invariantes Fund",
            "Crescent Cove Advisors",
            "Bloomberg Beta",
            "1517 Fund",
          ],
        },
        details3: {
          subTitle: "blockjoy [335]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Tribe Capital",
            "Renegade Ventures",
            "Draper Dragon",
            "Borderless Capital Bessemer Venture Partners",
          ],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    // fifth thread ----------------------------------------------------------------------------

    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp2: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp3: {
        img: index,
        name: "Index Ventures",
        deals: 8,
        value: "$1.5m",
        leadDays: 136.75,

        details1: {
          subTitle: "temporal [12765]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Sequoia Capital",
            "Madrona",
            "Greenoaks",
            "Amplify Partners",
            "Addition",
          ],
        },
        details2: {
          subTitle: "Causaly [38781]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Visionaries Club",
            "Marathon Venture Capital",
            "CONIQ Growth",
            "EBRD",
          ],
        },
        details3: {
          subTitle: "Hyperline [36507]",
          stage: "Seed",
          raised: "",
          co_investors: ["Kima Ventures", "Cocoa"],
        },
        details4: {
          subTitle: "matera [7368]",
          stage: "Series B",
          raised: "",
          co_investors: ["Mubadala Capital Ventures", "Bpifrance"],
        },
        details5: {
          subTitle: "weaviate [7329]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Zetta Venture Partners",
            "ING Ventures",
            "Cortical Ventures",
            "Battery Ventures",
          ],
        },
        details6: {
          subTitle: "covariant [15533]",
          stage: "Series C",
          raised: "",
          co_investors: [
            "Radical Ventures",
            "Northgate Capital",
            "Gates Frontier Fund",
            "Canada Pension Plan Investment Board",
            "Amplify Partners",
            "AIX Ventures",
          ],
        },
        details7: {
          subTitle: "Worldover io [30287]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Zetta Venture Partners",
            "ING Ventures",
            "Cortical Ventures",
            "Battery Ventures",
          ],
        },
      },
      comp4: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp5: {
        img: qed,
        name: "QED Investors",
        deals: 4,
        value: "$453.8m",
        leadDays: 60.8,
        details1: {
          subTitle: "finch [8578]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "PruVen Capital",
            "Menlo Ventures",
            "General Catalyst",
            "Altman Capital",
          ],
        },
        details2: {
          subTitle: "teamshares [9952]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Union Square Ventures",
            "Spark Capital",
            "Slow Ventures",
            "Khosla Ventures",
            "Inspired Capital Partners",
            "Contrary",
          ],
        },
        details3: {
          subTitle: "Carmoola [20517]",
          stage: "Debt Financing",
          raised: "",
          co_investors: [
            "VentureFriends",
            "NatWest Bank",
            "InMotion Ventures",
            "BCI Discovery",
          ],
        },
      },
    },

    // 6th thread -----------------------------------------------------------------------

    {
      comp1: {
        img: sequoia,
        name: "Sequoia Capital",
        deals: 10,
        value: "$1.9m",
        leadDays: 136.75,
        details1: {
          subTitle: "temporal [12765]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Sequoia Capital",
            "Madrona",
            "Greenoaks",
            "Amplify Partners",
            "Addition",
          ],
        },
        details2: {
          subTitle: "tiplink [4999]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Solana Ventures",
            "Octopus Ventures",
            "Paxos",
            "Multicoin Capital",
            "MonkeVentures",
            "Karatage",
            "Circle",
            "Asymmetric",
          ],
        },
        details3: {
          subTitle: "mirage [16065]",
          stage: "Seed",
          raised: "",
          co_investors: ["Pareto Holdings"],
        },
        details4: {
          subTitle: "Tavus [21405]",
          stage: "Seed",
          raised: "",
          co_investors: ["None"],
        },
        details5: {
          subTitle: "linear [4662]",
          stage: "Series B",
          raised: "",
          co_investors: ["Accel", "01 Advisors"],
        },
        details6: {
          subTitle: "Apollo.io [10018]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Tribe Capital",
            "Nexus Venture Partners",
            "Bain Capital Ventures",
          ],
        },
        details7: {
          subTitle: "Buidler DAO [17812]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "SevenX Ventures",
            "Gate Labs",
            "DRK Lab",
            "Conflux Network",
            "Bing Ventures",
          ],
        },
        details8: {
          subTitle: "cyera [378]",
          stage: "Series B",
          raised: "",
          co_investors: ["Redpoint", "Cyberstarts", "Accel"],
        },
        details9: {
          subTitle: "layerzero labs [2029]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Samsung NEXT",
            "OpenSea Ventures",
            "OKX Ventures",
            "CryptoViet Ventures",
            "Circle Ventures",
            "BOND",
            "a16z crypto",
          ],
        },
      },
      comp2: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    // 7th thread -------------------------------------------------------

    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },

    // DUMMYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
 
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
    {
      comp1: { img: "", name: "", deals: 0, value: "", leadDays: 0 },

      comp2: {
        img: alumni,
        name: "Alumni Ventures",
        deals: 12,
        value: "$692.1m",
        leadDays: 48.3,
        details1: {
          subTitle: "Hawkeye 360 [2512]",
          stage: "Series D",
          raised: "",
          co_investors: [
            "Strategic Development Fund",
            "Razor’s Edge Ventures",
            "NightDragon",
            "Manhattan Venture Partners",
            "Insight Partners",
            "BlackRock",
            "Adage Capital Management",
          ],
        },
        details2: {
          subTitle: "Hyfe [20779]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "XFactor Ventures",
            "The Engine",
            "Synthesis Capital",
            "Supply Change Capital",
            "Refactor Capital",
            "Overwater Ventures",
          ],
        },
        details3: {
          subTitle: "Spartan Radar [19933]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Prime Movers Lab",
            "Microsfot",
            "MaC Venture Capital",
            "IronGate Capital Advisors",
            "Gaingels",
            "8VC",
          ],
        },
        details4: {
          subTitle: "Scythe Robotics [19776]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "True Ventures",
            "Inspired Capital Partners",
            "Energy Impact Partners",
            "ArcTern Ventures",
            "Amazon Alexa Fund",
          ],
        },
        details5: {
          subTitle: "Train Fitness [35537]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Spacecadet Ventures",
            "Republic Capital",
            "Relay Ventures",
            "Mana Ventures",
            "Gambit Partners",
            "Boost VC",
            "BAM Ventures",
            "Anorak Ventures",
          ],
        },
        details6: {
          subTitle: "Rwazi [22209]",
          stage: "Seed",
          raised: "",
          co_investors: ["Bonfire Ventures"],
        },
        details7: {
          subTitle: "Enfabrica [38404]",
          stage: "Series B",
          raised: "",
          co_investors: [
            "Valor Equity Partners",
            "Sutter Hill Ventures",
            "NVIDIA",
            "Liberty Global Ventures",
            "Infinitum Partners",
            "IAG Capital Partners",
            "Atreides Management",
          ],
        },
        details8: {
          subTitle: "Alix [38069]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Scribble Ventures",
            "Magnify Ventures",
            "Initialized Capital",
            "American Family Ventures",
          ],
        },
        details9: {
          subTitle: "Treehouse [22810]",
          stage: "Series A",
          raised: "",
          co_investors: [
            "Virta Ventures",
            "Trucks Venture Capital",
            "Montage Ventures",
            "Invest Detroit",
            "Holman Growth Ventures",
            "Gutter Capital",
            "Detroit Venture Partners",
            "CarMax",
            "Automotive Ventures",
            "Assurabt Ventures",
            "Acrew Capital",
          ],
        },
        details10: {
          subTitle: "Cohart [32353]",
          stage: "Seed",
          raised: "",
          co_investors: [
            "Wilson Sonsini Goodrich & Rosati",
            "Slauson & Co.",
            "Courtside Ventures",
            "BDMI",
            "11:11 Media",
          ],
        },
        details11: {
          subTitle: "TeachMe.To [61865]",
          stage: "Seed",
          raised: "",
          co_investors: ["Gravity Capital", "1984 Ventures"],
        },
      },
      comp3: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
      comp6: { img: "", name: "", deals: 0, value: "", leadDays: 0 },
    },
  ],
};
